name: pizza_repository
description: The repo that handles the pizzas
publish_to: none
version: 0.0.1


environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.4

flutter:
  uses-material-design: true  # Added here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
